version: "3"

services:
  wg-dynamic-server:
    image: wg-dynamic-server:local-earthly-testing # this comes from Earthfile reference with --load flag
    ports:
      - 51901:51900
    networks:
      wg-dynamic-net:
        ipv4_address: 10.10.1.10
  wg-dynamic-client:
    image: wg-dynamic-client:local-earthly-testing # this comes from Earthfile reference with --load flag
    ports:
      - 51902:51900
    networks:
      wg-dynamic-net:
        ipv4_address: 10.10.1.11
networks:
  wg-dynamic-net:
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: "10.10.1.0/24"
